// Copyright (c) Microsoft. All rights reserved.

import express from "express";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./routes"; // Auto-generated by tsoa
import { log } from "./libs/CommonTypeScript/src";


const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

// Register tsoa-generated routes
RegisterRoutes(app);

// Serve Swagger UI
app.use("/docs", swaggerUi.serve, swaggerUi.setup(require("./swagger.json")));

// Start server
app.listen(PORT, () => {
    log.info(`Server running on http://localhost:${PORT}`);
    log.info(`Swagger UI available at http://localhost:${PORT}/docs`);
});
