# Default command when no command is provided
_default:
    @just --list

# List docker containers
ps:
    @docker compose ps

# Start all services
start:
    @docker compose up --detach --pull always

# Stop all services
stop:
    @docker compose down

# Restart all services
restart:
    @docker compose restart

# Show real time stats from the services
stats:
    @docker compose stats

# Show combined logs
log:
    @docker compose logs --follow

# Show combined logs with timestamps
logs:
    @docker compose logs --follow --timestamps
